Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	
	config.vm.provider "virtualbox" do |v|
		#Количество ОЗУ для ВМ
		v.memory = "512"
        
		#Количество CPU для ВМ
		v.cpus = "1"
		
		#Имя ВМ в окружении Vagrant
		v.name = "jira"

	config.vm.provision "copy-files",
		type: "file",
		preserve_order: true,
		source: "./config/.",
		destination: "~/"

	config.vm.provision "do-things",
		type: "shell",
		preserve_order: true,
		inline: <<-SHELL
		setenforce 0
		yum install java-1.8.0-openjdk.x86_64 -y	
		curl https://product-downloads.atlassian.com/software/jira/downloads/atlassian-jira-software-8.5.4.tar.gz -o atlassian-jira-software-8.5.4.tar.gz
		mkdir -p /opt/atlassian/jira
		tar -xzf atlassian-jira-software-8.5.4.tar.gz
		mv /home/vagrant/atlassian-jira-software-8.5.4-standalone/* /opt/atlassian/jira
		mv /home/vagrant/jira.* /etc/systemd/system/
		systemctl daemon-reload
		systemctl enable jira.socket
		systemctl start jira.socket
		ss -tnulp | grep 8080
		SHELL
	end
end