Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
        config.vm.synced_folder "./", "/mnt/vagrant"		
	config.vm.provider "virtualbox" do |v|
		v.memory = "512"
        	v.cpus = "2"
			
	end
end
