Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
		
	config.vm.provider "virtualbox" do |v|
		#Количество ОЗУ для ВМ
		v.memory = "768"
        
		#Количество CPU для ВМ
		v.cpus = "2"
		
		#Имя ВМ в окружении Vagrant
		v.name = "docker"
	end
end
