Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	
	config.vm.provider "virtualbox" do |v|
		#Количество ОЗУ для ВМ
		v.memory = "512"
        
		#Количество CPU для ВМ
		v.cpus = "1"
		
		#Имя ВМ в окружении Vagrant
		v.name = "httpd"

	config.vm.provision "copy-files",
		type: "file",
		preserve_order: true,
		source: "./config/.",
		destination: "~/"

	config.vm.provision "do-things",
		type: "shell",
		preserve_order: true,
		inline: <<-SHELL
		yum install httpd -y
		setenforce 0	
		mv /home/vagrant/httpd-* /etc/sysconfig
		mv /home/vagrant/*.service /etc/systemd/system/
		mv /home/vagrant/*.conf /etc/httpd/conf/
		systemctl daemon-reload
		systemctl start httpd@first
		systemctl start httpd@second
		ss -tnulp | grep httpd
		SHELL
	end
end