Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	
	config.vm.provider "virtualbox" do |v|
		#Количество ОЗУ для ВМ
		v.memory = "512"
        
		#Количество CPU для ВМ
		v.cpus = "1"
		
		#Имя ВМ в окружении Vagrant
		v.name = "httpd"

	config.vm.provision "copy-files",
		type: "file",
		preserve_order: true,
		source: "./config/.",
		destination: "~/"

	config.vm.provision "do-things",
		type: "shell",
		preserve_order: true,
		inline: <<-SHELL
		yum install epel-release -y && yum install spawn-fcgi php php-cli mod_fcgid httpd -y		
		mv /home/vagrant/spawn-fcgi /etc/sysconfig
		mv /home/vagrant/spawn-fcgi.service /etc/systemd/system/
		systemctl daemon-reload
		systemctl start spawn-fcgi
		systemctl status spawn-fcgi
		SHELL
	end
end