version: '3.3'
services:
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        networks:
            nginxphp:
                aliases: 
                    - nginx.nginxphp
        depends_on:
            - php
    
    php:
        build: ./php
        ports:
            - "9000:9000"
        networks:
            nginxphp:
                aliases:
                    - php.nginxphp

networks:
    nginxphp: