version: '3.3'
services:
    nginx:
        image: looklikethatguy/nginxphp:v1
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/www
        networks:
            - nginxphp
        depends_on:
            - php
    
    php:
        image: looklikethatguy/phpfm:v1
        container_name: php
        volumes:
            - ./www:/www
        ports:
            - "9000:9000"
        networks:
            - nginxphp
                
networks:
    nginxphp: